name: ytdownloader
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^2.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  starflut: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/yt_downloader.py
